#!/bin/bash

git clone --depth 1 https://github.com/Shougo/neomru.vim.git
git clone --depth 1 https://github.com/Shougo/unite-outline.git
git clone --depth 1 https://github.com/Shougo/unite.vim.git
git clone --depth 1 https://github.com/Shougo/vimfiler.git
git clone --depth 1 https://github.com/Shougo/vimproc.git
git clone --depth 1 https://github.com/Shougo/vimshell.git
git clone --depth 1 https://github.com/digitaltoad/vim-jade.git
git clone --depth 1 https://github.com/digitaltoad/vim-pug.git
git clone --depth 1 https://github.com/fuenor/im_control.vim.git
git clone --depth 1 https://github.com/hail2u/vim-css3-syntax.git
git clone --depth 1 https://github.com/hari-rangarajan/CCTree.git
git clone --depth 1 https://github.com/itchyny/lightline.vim.git
git clone --depth 1 https://github.com/junegunn/vim-easy-align.git
git clone --depth 1 https://github.com/kana/vim-fakeclip.git
git clone --depth 1 https://github.com/kchmck/vim-coffee-script.git
git clone --depth 1 https://github.com/kshenoy/vim-signature.git
git clone --depth 1 https://github.com/luochen1990/rainbow
git clone --depth 1 https://github.com/majutsushi/tagbar
git clone --depth 1 https://github.com/mileszs/ack.vim.git
git clone --depth 1 https://github.com/othree/html5.vim
git clone --depth 1 https://github.com/pangloss/vim-javascript
git clone --depth 1 https://github.com/previm/previm.git
git clone --depth 1 https://github.com/rafi/awesome-vim-colorschemes.git
git clone --depth 1 https://github.com/rking/ag.vim
git clone --depth 1 https://github.com/ryanoasis/vim-devicons.git
git clone --depth 1 https://github.com/sgur/vim-editorconfig.git
git clone --depth 1 https://github.com/slim-template/vim-slim.git
git clone --depth 1 https://github.com/t9md/vim-quickhl.git
git clone --depth 1 https://github.com/thinca/vim-ref.git
git clone --depth 1 https://github.com/tpope/vim-fugitive.git
git clone --depth 1 https://github.com/vim-jp/vimdoc-ja.git
git clone --depth 1 https://github.com/vim-scripts/Align.git
git clone --depth 1 https://github.com/vim-scripts/CodeReviewer.vim.git
git clone --depth 1 https://github.com/vim-scripts/ScrollColors.git
git clone --depth 1 https://github.com/vim-scripts/vcscommand.vim.git
